---
title: "Tmux安装配置使用教程"
date: 2023-11-22T01:26:22+08:00
draft: false
---

* 基本用法

** 启动与退出

在终端键入tmux命令，启动 Tmux

Ctrl+d或者输入exit命令，退出 Tmux

** 前缀键

Tmux
窗口有大量的快捷键，默认的前缀键是Ctrl+b，即先按下Ctrl+b，然后再按下其他按键

比如，帮助命令的快捷键是Ctrl+b ?。在Tmux窗口中，先按下Ctrl+b，再按下?，就会显示帮助信息，然后，按下 ESC 键或q键，就可以退出帮助。

** tmux滚动窗口

按Ctrl+b，再按[，就可以用鼠标滑轮滚动了，按q退出。

*** 参考链接

[[https://blog.csdn.net/weixin_40833196/article/details/88079785][tmux滚动窗口]]

** tmux调整多窗格比例

按Ctrl+b，再按方向键就可以调整窗格比例了，例如调整上下两个窗格的比例，按Ctrl+b，再按上下方向键就可以了，如果是调整左右两个窗格的比例，按Ctrl+b，再按左右方向键就可以了，

** 会话管理

*** 新建会话

第一个启动的 Tmux窗口，编号是0，第二个窗口的编号是1

除默认运行tmux是以编号进行区分，还可以创建指定名称的会话。
 
#+begin_src bash
  tmux new -s <session-name>  
#+end_src

*** 离线创建会话

#+begin_src 
tmux new -d
或
tmux new -d -s <session-name>
#+end_src

*** 分离会话

Tmux 窗口中，按下Ctrl+b d或者输入"tmux detach"命令，就会将当前会话与窗口分离。 

tmux ls命令可以查看当前所有的 Tmux 会话。

#+begin_src bash
  tmux ls
  或者
  tmux list-session   
#+end_src

*** 接入会话

tmux attach命令用于重新接入某个已存在即之前分离的会话。
 
通过会话编号接入会话

#+begin_src bash
  tmux attach -t 0
#+end_src

通过会话名称接入会话

#+begin_src bash
  tmux attach -t <session-name>
#+end_src

*** 杀死会话

通过会话编号杀死会话

#+begin_src bash
  tmux kill-session -t 0
#+end_src

通过会话名称杀死会话

#+begin_src bash
  tmux kill-session -t <session-name>
#+end_src

*** 切换会话

通过会话编号切换会话

#+begin_src bash
  tmux switch -t 0
#+end_src


通过会话名称切换会话

#+begin_src bash
  tmux switch -t <session-name>
#+end_src

重命名会话

#+begin_src bash
  tmux rename-session -t 0 <new-name>
#+end_src

上面命令将0号会话重命名。

*** 会话快捷键

下面是一些会话相关的快捷键。

- Ctrl+b d：分离当前会话。
- Ctrl+b s：列出所有会话。
- Ctrl+b $：重命名当前会话。

** 最简操作流程

综上所述，以下是 Tmux 的最简操作流程。

新建会话tmux new -s my_session。
在 Tmux 窗口运行所需的程序。
按下快捷键Ctrl+b d将会话分离。
下次使用时，重新连接到会话tmux attach-session -t my_session。

** 窗格操作

Tmux可以将窗口分成多个窗格（pane），每个窗格运行不同的命令。以下命令都是在 Tmux 窗口中执行。

划分上下两个窗格

#+begin_src bash
  tmux split-window
#+end_src

划分左右两个窗格

#+begin_src bash
  tmux split-window -h
#+end_src

*** 移动光标

光标切换到上方窗格

#+begin_src bash
  tmux select-pane -U
#+end_src

光标切换到下方窗格

#+begin_src bash
  tmux select-pane -D
#+end_src

光标切换到左边窗格

#+begin_src bash
  tmux select-pane -L
#+end_src

光标切换到右边窗格

#+begin_src bash
  tmux select-pane -R
#+end_src

*** 交换窗格位置

当前窗格上移

#+begin_src bash
  tmux swap-pane -U
#+end_src

当前窗格下移

#+begin_src bash
  tmux swap-pane -D
#+end_src

*** 窗格快捷键

下面是一些窗格操作的快捷键。

#+begin_src bash
  Ctrl+b %：划分左右两个窗格。
  Ctrl+b "：划分上下两个窗格。
  Ctrl+b <arrow key>：光标切换到其他窗格。<arrow
  key>是指向要切换到的窗格的方向键，比如切换到下方窗格，就按方向键↓。
  Ctrl+b ;：光标切换到上一个窗格。
  Ctrl+b o：光标切换到下一个窗格。
  Ctrl+b {：当前窗格与上一个窗格交换位置。
  Ctrl+b }：当前窗格与下一个窗格交换位置。
  Ctrl+b
  Ctrl+o：所有窗格向前移动一个位置，第一个窗格变成最后一个窗格。
  Ctrl+b
  Alt+o：所有窗格向后移动一个位置，最后一个窗格变成第一个窗格。
  Ctrl+b x：关闭当前窗格。
  Ctrl+b !：将当前窗格拆分为一个独立窗口。
  Ctrl+b z：当前窗格全屏显示，再使用一次会变回原来大小。
  Ctrl+b Ctrl+<arrow key>：按箭头方向调整窗格大小。
  Ctrl+b q：显示窗格编号。

#+end_src

** 窗口管理

除了将一个窗口划分成多个窗格，Tmux 也允许新建多个窗口。

新建一个指定名称的窗口

#+begin_src bash
  tmux new-window -n <window-name>
#+end_src

*** 切换窗口

切换到指定编号的窗口

#+begin_src bash
  tmux select-window -t <window-number>
#+end_src

切换到指定名称的窗口

#+begin_src bash
  tmux select-window -t <window-name>
#+end_src

*** 重命名窗口

#+begin_src bash
  tmux rename-window <new-name>
#+end_src 

*** 窗口快捷键

下面是一些窗口操作的快捷键。

#+begin_src bash
  Ctrl+b c：创建一个新窗口，状态栏会显示多个窗口的信息。
  Ctrl+b p：切换到上一个窗口（按照状态栏上的顺序）。
  Ctrl+b n：切换到下一个窗口。
  Ctrl+b
  <number>：切换到指定编号的窗口，其中的<number>是状态栏上的窗口编号。
  Ctrl+b w：从列表中选择窗口。
  Ctrl+b ,：窗口重命名。
#+end_src

** 其他命令

列出所有快捷键，及其对应的 Tmux 命令

#+begin_src bash
  tmux list-keys
#+end_src

列出所有 Tmux 命令及其参数

#+begin_src bash
  tmux list-commands
#+end_src

列出当前所有 Tmux 会话的信息

#+begin_src bash
  tmux info
#+end_src

重新加载当前的 Tmux 配置

#+begin_src bash
  tmux source-file ~/.tmux.conf
#+end_src

* tmux发送到某个会话指定命令/按键

#+begin_src bash
tmux send-keys [-t <session-name>] <key>
#+end_src

例如，向会话mc发送指令ls并按回车执行
#+begin_src bash
tmux send-keys -t mc ls Enter
#+end_src

向会话mc发送bash start.sh并按回车执行
#+begin_src bash
tmux send-keys -t mc bash Space start.sh Enter
#+end_src

** 参考链接

[[https://www.cnblogs.com/wangbingbing/p/16473526.html][tmux发送到某个会话指定命令/按键]]

* 安装方法

** 安装

Tmux 一般需要自己安装。

** git-bash安装tmux

git bash中执行以下命令，即可安装tmux。如果以下操作完tmux没法使用，注意git升级到最新版，我遇到的坑就是git2.9版本安装完tmux后打tmux命令没反应。升级完git2.26后即可。

#+begin_src bash :tangle :no-expand
  git clone https://github.com/xnng/bash.git
  cd bash
  cp tmux/bin/* /usr/bin
  cp tmux/share/* /usr/share -r
#+end_src

*** 配置tmux

新建tmux配置文件

#+begin_src bash
  vim ~/.tmux.conf
#+end_src

*** 复制如下配置到刚才新建的配置文件中即可

#+begin_src bash
  setw -g mouse
  set-option -g history-limit 20000
  set-option -g mouse on
  bind -n WheelUpPane select-pane -t= \; copy-mode -e \; send-keys -M
  bind -n WheelDownPane select-pane -t= \; send-keys -M
#+end_src

** 一键安装配置脚本

为便安装与配置tmux，特地将所有需要操作的内容都写到脚本里了，到时候只要打开git-bash，然后运行该脚本就可以了

[[resources/install_tmux.zip][点击下载脚本]]

执行脚本

#+begin_src bash
  source install_tmux.sh
#+end_src
 
** Ubuntu 或 Debian

#+begin_src bash
  sudo apt-get install tmux
#+end_src

** CentOS 或 Fedora

#+begin_src bash
  sudo yum install tmux  
#+end_src

** Mac

#+begin_src bash
  brew install tmux  
#+end_src

* 参考链接

[[https://www.jianshu.com/p/2defec71e2de][git bash安装tmux实现多标签]]

[[https://www.ruanyifeng.com/blog/2019/10/tmux.html][Tmux 使用教程]]

