---
title: Emacs管理密码
tags: ["pass", "emacs"]
date: 2025-08-08T16:32:17.65+0800
---

* 折腾在Emacs里管理密码
<2025-08-08 Friday 15:36>

** termux安装pass

#+begin_src bash
apt install -y pass
#+end_src

** 创建gpg密钥

#+begin_src bash
gpg --full-generate-key
#+end_src
按照提示创建密钥，注意记下其 ID。您应该使用默认密钥类型（RSA 和 RSA），但将密钥大小更改为 4,096 位以获得最大安全性。

使用可用的 GPG 密钥，您现在可以初始化 pass。运行以下命令，将 placeholder-gpg-id 替换为您自己的 GPG ID 或 pub 。
#+begin_src bash
pass init placeholder-gpg-key
#+end_src

*** 更新gpg密码

创建密钥的最后会让你设置一个密码短语，有时候可能会想更新密码短语。

#+begin_src bash
gpg --list-keys                 # 列出所有gpg密钥，找到想要更新密码的对应密钥的id
gpt --edit-key ynpass           # ynpass为我要更新密码的密钥的id，进入命令行执行passwd，然后先输入旧的密码，然后创建新的密码
#+end_src

** emacs配置

#+begin_src emacs-lisp
(use-package pass
  :ensure t
  :commands (pass)
  )
#+end_src
安装完后，我们可以通过 M-x pass 的方式来管理密码了。

我们最主要使用到的两个操作是：

|---------+-----------------------------------------------|
| i       | insert, 插入一个新的密码                      |
|---------+-----------------------------------------------|
| j       | Jump to Entry, 跳转到我们想要的密码，查看密码 |
|---------+-----------------------------------------------|
| C-c,C-c | 查看密码                                      |
|---------+-----------------------------------------------|

** 插入新密码 

我们在 pass 的界面按下 i 键后，会提示让我们输入 Password entry ，我们以 Email/example.com 为例来新建一个邮箱密码（Email这个目录是为了将密码分门别类，维护和可视化更加直观，核心在于 exmaple.com 这个邮箱所在的网站地址）。然后，它会提示你输入 Password ，以及 Confirm password ，两次密码必须输入一致。然后就添加成功了。此时，只有关于 example 的密码，还没有登录名信息，我们会在下个小节讲如何添加登录信息。

** 查看一个密码

我们按下 j 键，通过 vertico 补全框架定位到 exmaple.com，光标会自动跳转到 example.com 这个条目上，然后按下回车。此时，根据它的提示，按下 C-c C-c 可以显示或者修改密码。这里，我们还需要增加一个信息，就是邮箱的登录名，我们添加一个 login 的信息如下：
#+begin_src bash
login: randolph@example.com
#+end_src
然后保存即可。

** 参考链接

[[https://remacs.fun/posts/面向产品经理的emacs教程28.-在emacs里管理密码/][面向产品经理的Emacs教程：28. 在Emacs里管理密码]]

[[https://cn.linux-console.net/?p=7397][如何使用 Pass，Linux 系统的命令行密码管理器]]

[[https://blog.csdn.net/willingtolove/article/details/122362705][GPG使用方法总结（密钥管理，加解密文件）]]

[[https://nyk.ma/posts/password-store/#条目结构][pass : 密码管理本不复杂#条目结构]]

[[https://blog.csdn.net/gitblog_00972/article/details/142021455][pass-import 项目教程]]
