---
title: org-mode任务管理
tags: ["emacs", "org-mode", "任务管理"]
date: 2024-11-25T03:12:37.76+0800
---

* org-mode任务管理

大多数内容看参考链接内容即可，本文章只列出一些简单的配置，并补充一些内容

某org文件标题被标记了状态如 TODO、DONE，然后打开该文件执行快捷键 C-c [ 将文件添加入 org-agenda追踪列表，然后执行 org-agenda，在 org-agenda 的窗口中按字母 a 显示本周任务，如果要将追踪的文件移出去，可以执行快捷键 C-c ]。

** 任务管理方案

*** 直接插入文件头的任务管理配置

只需要任意一个任务状态设置快捷键即可，其他会默认以任务状态开头字母小写形式表现出来
#+begin_src 
#+SEQ_TODO: REPORT(@/!) BUG(@/!) KNOWNCAUSE(@/!) | FIXED(!)
#+SEQ_TODO: TODO(t!) | DONE(!) CANCELED(@/!)
#+end_src
将光标放在这些内容上，输入 C-c C-c 可以直接生效。然后再在用 C-c C-t 即可设置任务状态了。

*** 任务管理配置文件

只需要任意一个任务状态设置快捷键即可，其他会默认以任务状态开头字母小写形式表现出来
#+begin_src 
(setq org-todo-keywords
      '((sequence "REPORT(@/!)" "BUG(@/!)" "KNOWNCAUSE(@/!)" "|" "FIXED(!)")
	(sequence "TODO(t!)" "|" "DONE(!)" "CANCELED(@/!)")
	))

(global-set-key "\C-cl" 'org-store-link)
(global-set-key "\C-cc" 'org-capture)
(global-set-key "\C-ca" 'org-agenda)
#+end_src

** 设置任务等级的方式

在Org-mode中，还针对任务设定了A，B，C三种优先级，在安排日程的时候可以按照优先级进行排序。为任务设定优先级是通过快捷键
S-UP/DOWN 。

除了 S-UP/DOWN 外，还可以通过快捷键 C-c,C-, 来设置任务优先级

** org-store-link 

org-store-link 是 Org Mode 中的一个命令，用于将当前缓冲区（比如文件、网页或其他内容）的链接保存到 Org Mode 的链接列表中。这对于创建和管理任务和笔记时非常有用，尤其是当你希望在 Org 文件中引用外部资源时。

示例
假设你正在浏览一个网页，并希望将其链接保存在 Org 文件中：
- 打开网页或文档，按 C-c l （或 M-x org-store-link）。
- Org Mode 会将该网页的链接（或者文件名）存储在链接列表中。
- 接下来，回到你的 Org 文件，按 C-c C-l 来插入这个链接。

** org-capture

org-capture 是 Org Mode 中的一个命令，允许你快速创建和捕捉新的条目到指定的 Org 文件。通常用于快速记录任务、笔记或者其他相关信息。

** org-agenda

org-agenda 是 Org Mode 中的命令，用于显示日程、任务列表以及其他时间表相关的视图。它可以帮助你查看和管理任务的安排。

** 快速插入时间戳

*** C-c !

直播插入时间戳，只包含年月日，不包含小时和分钟。

*** C-c .

可以自定义时间戳，默认是插入年月日，手动输入小时和分钟即可，后边还可以添加定期提醒的选项，这方面我还不太熟练。

*** 计划时间和截止时间

设置计划时间和截止时间，同样默认是插入年月日，可以自定义时间戳，手动输入小时和分钟即可。

** 参考链接

[[https://holbrook.github.io/2012/04/14/emacs_orgmode_task.html][org-mode，最强的任务管理利器，没有之一]]
