[comments]
  enabled = true
  provider = "giscus"
  [comments.giscus]
      repo = "ynhugo/ynhugo.github.io"
      repoID = "R_kgDOSnA4MQ"
      category = "Announcements"
      categoryID = "DIC_kwDOSnA4Mc4C9zNa"
      mapping = "pathname"
      lightTheme = "light"
      darkTheme = "dark"
      reactionsEnabled = 1
      emitMetadata = 0
