---
title: "Windows更改系统版本"
tags: ["windows"]
date: 2023-11-04T17:40:37+08:00
draft: false
---

对于新买电脑的人来说，一般电脑预装的系统是家庭版或家庭中文版，其它版本都有的功能家庭版却没有。尤其是远程桌面，Windows最基本的功能它也没有,而重装系统又要花很多时间和精力。那么怎样才能更改系统版本呢？下面介绍常用方法（对Win11同样实用）
** 输入产品密钥更改系统版本
Win10系统更换版本的方法很简单，如家庭版系统想要更换为专业版，只需要在"设置->更新和安全->激活->更改产品密钥"里输入win10专业版的产品密钥即可，但需要有专业版的密钥才行。更换其他版本同理。

Win11系统更换版本的方法很简单，同时按Win+i键打开设置，左侧点击“系统”，右侧点击“激活”，点击“更改产品密钥”，"更改产品密钥"里输入win11专业版的产品密钥即可，但需要有专业版的密钥才行。
** 提供密钥
*** 密钥参考
这里提供win10企业版密钥：
#+begin_src emacs-lisp :tangle no
  NRTT2-86GJM-T969G-8BCBH-BDWXG
#+end_src

这里提供win11专业版密钥
#+begin_src emacs-lisp :tangle no
  WMN7B-Y7TKF-Y49QB-TMQ8T-GMT6T
#+end_src

如果上面密钥失效了可以自己在网上再找，如果是win10系统要更改系统版本，那就找对应win10系统的专业版密钥，win11同样如此。
*** 密钥获取来源参考

[[https://zhuanlan.zhihu.com/p/534116690][永久激活Windows10系统的三种方式]]


** 更改后如果电脑提示未激活需要再次激活
更改系统版本过程中系统会自动重启，如果重启之后系统提示没有激活，那么可以自己下载激活软件激活一下，这里提供一些我常用的激活方法
*** 软件激活

软件下载：[[resources/激活工具.zip][windows激活工具下载]]

*** 脚本激活

脚本下载：[[resources/Windows一键激活脚本.zip][Windows一键激活脚本.zip]]

开源；单文件；数字激活、KMS38激活、KMS在线激活；可激活Windows和Office。

推荐使用，开源脚本代码更安全，系统不会提示病毒危险，激活后即可删除。
