---
title: "Linux内核编译"
date: 2023-09-08T23:19:12+08:00
draft: false
---
* 系统自带的内核树
有时，安装的系统已经自带了Linux内核树，足够用来编译驱动程序了。
自带的内核树通常位于
#+begin_src c :tangle no
  /lib/modules/<系统内核版本>/build
#+end_src
其中，系统内核版本可以用uname -r来查看

#+begin_src c :tangle no
  $ uname -r
  5.11.0-41-generic
#+end_src
* 环境配置
初次配置内核树要先安装一些必要的环境
#+begin_src c :tangle no
  sudo apt-get build-dep linux linux-image-$(uname -r)
#+end_src
如果报错Error :: You must put some ‘source‘ URIs in your sources.list，请按照如下操作进行。
解决方法
输入下面三行即可。
#+begin_src c :tangle no
  sudo cp /etc/apt/sources.list /etc/apt/sources.list~
  sudo sed -Ei 's/^# deb-src /deb-src /' /etc/apt/sources.list
  sudo apt-get update
#+end_src
除了上面的环境之外，还要安装这些
#+begin_src c :tangle no
  sudo apt-get install libncurses-dev gawk flex bison openssl libssl-dev dkms libelf-dev libudev-dev libpci-dev libiberty-dev autoconf dwarves
#+end_src
* 下载源码
#+begin_src c :tangle no
  sudo apt-get source linux-image-unsigned-$(uname -r)
#+end_src
这一步结束之后，会多出三个文件（可以删除），
#+begin_src c :tangle no
  linux-hwe-5.11_5.11.0-41.45~20.04.1.diff.gz
  linux-hwe-5.11_5.11.0-41.45~20.04.1.dsc
  linux-hwe-5.11_5.11.0.orig.tar.gz
#+end_src
以及一个文件夹（内核源码所在的文件夹）
#+begin_src c :tangle no
  linux-hwe-5.11-5.11.0
#+end_src
（注：文件名称根据不同的系统版本会有所不同）
* 构建准备
（注：任何时候，运行命令时遇见了permission denied，只需要在命令开头加上sudo后重新运行即可）
进入linux-hwe-5.11-5.11.0文件夹，输入
#+begin_src c :tangle no
  make menuconfig
#+end_src
什么都不用修改，直接关闭界面即可（方向键选择Exit然后回车，或者连续按两下Esc就能退出），在退出的时候会提示是否保存，按照提示保存一下，这样会在当前目录下生成一个.config文件（输入ls -a就能找到这个文件），保证稍后的make能够顺利执行。
* 构建内核
为了防止make中的make modules_install环节失败， 请先运行下面的命令
#+begin_src c :tangle no
  sudo scripts/config --set-str SYSTEM_TRUSTED_KEYS ""
#+end_src
输入下面的命令开始构建（如遇见permission denied，在命令开头加上sudo后重新运行即可）
#+begin_src c :tangle no
  make
#+end_src
这里要狠狠地等一会儿，一般要一到数个小时。可以通过-j <最大并发任务数>命令，使用并发来提速。最大并发任务数一般可以是CPU数量的两倍。
注：通过使用make help进行查阅可以发现，在输入make时，会自动执行 1）make vmlinux（构建原始内核） 2）make bzImage（构建压缩的内核）和 3） make modules（单独构建模块化的驱动）这三个动作）
* 安装模块
最后，把模块安装到/lib/modules/$(uname -r)目录
#+begin_src c :tangle no
  sudo make modules_install 
#+end_src
* 参考链接：
link:https://blog.csdn.net/weixin_39591031/article/details/121710076
link:https://blog.csdn.net/weixin_39591031/article/details/121696825
