---
title: ubuntu24.04安装仓颉工具链
tags: ["仓颉语言", "Linux", "Ubuntu"]
date: 2025-06-22T22:20:37.33+0800
---

* ubuntu24.04安装仓颉工具链

** Linux 版本工具链的支持与安装

*** Ubuntu 24.04

#+begin_src bash
  sudo apt-get install -y  binutils gcc make libc6-dev libc++-dev libgcc-9-dev
#+end_src

**** 参考链接

[[https://docs.cangjie-lang.cn/docs/0.53.18/user_manual/source_zh_cn/Appendix/linux_toolchain_install.html#适用于各-linux-发行版的仓颉工具链依赖安装命令][适用于各 Linux 发行版的仓颉工具链依赖安装命令]]

** 编译安装依赖工具

*** OpenSSL 3

从以下链接可以下载到 OpenSSL 3 的源码：

https://www.openssl.org/source/old/

建议使用 OpenSSL 3.0.7 或更高版本。

此处以 OpenSSL 3.0.7 为例，下载后使用以下命令解压压缩包：
#+begin_src bash
  tar xf openssl-3.0.7.tar.gz
#+end_src

解压完成后进入目录：
#+begin_src bash
  cd openssl-3.0.7
#+end_src

编译 OpenSSL：

注意：

如果系统已经安装了 OpenSSL，建议使用 --prefix=<path> 选项指定一个自定义安装路径，例如 --prefix=/usr/local/openssl-3.0.7 或开发者的个人目录。在系统目录已经存在 OpenSSL 的场景下直接使用以下命令编译安装可能会使系统 OpenSSL 被覆盖，并导致依赖系统 OpenSSL 的应用不可用。

#+begin_src bash
  ./Configure --libdir=lib --prefix=/usr/local/openssl-3.0.7
  make -j$(nproc)
#+end_src

测试 OpenSSL：
#+begin_src bash
  make -j$(nproc) test
#+end_src

将 OpenSSL 安装至系统目录（或先前指定的 --prefix 目录），可能需要提供 root 权限以成功执行以下命令：
#+begin_src bash
  make install
  # 或
  sudo make  -j$(nproc) install
#+end_src

如果先前编译 OpenSSL 时没有通过 --prefix 设置自定义安装路径，则 OpenSSL 安装已经完成了。如果先前通过 --prefix 指定了自定义的安装路径，还需要设置以下变量，以使仓颉工具链可以找到 OpenSSL 3。

注意：

如果系统中原先存在其他版本的 OpenSSL，通过以下方式配置后，除了仓颉工具链外，其他编译开发工具默认使用的 OpenSSL 版本也可能受到影响。如果使用其他编译开发工具时出现 OpenSSL 不兼容的情况，请仅为仓颉开发环境配置以下变量。

请将 <prefix> 替换为指定的自定义安装路径。
#+begin_src bash
  # export LIBRARY_PATH=<prefix>/lib:$LIBRARY_PATH
  # export LD_LIBRARY_PATH=<prefix>/lib:$LD_LIBRARY_PATH
  export LIBRARY_PATH=/usr/local/openssl-3.0.7/lib:$LIBRARY_PATH
  export LD_LIBRARY_PATH=/usr/local/openssl-3.0.7/lib:$LD_LIBRARY_PATH
#+end_src

通过以上方式所配置的环境变量仅在当前执行命令的 shell 会话窗口有效。若希望 shell 每次启动时都自动配置，可以在 =$HOME/.bashrc= 、 =$HOME/.zshrc= 或其他 shell 配置文件（依开发者的 shell 种类而定）加入以上命令。

若希望配置可以默认对所有用户生效，可以执行以下命令：

请将 <prefix> 替换为指定的自定义安装路径。
#+begin_src bash
  sudo chown -R $USER:$USER /etc/profile  
  echo "export LIBRARY_PATH=/usr/local/openssl-3.0.7/lib:$LIBRARY_PATH" /etc/profile
  sudo chown -R root:root /etc/profile
  source /etc/profile

  sudo chown -R $USER:$USER /etc/ld.so.conf
  echo "export LD_LIBRARY_PATH=/usr/local/openssl-3.0.7/lib:$LD_LIBRARY_PATH" /etc/ld.so.conf
  sudo chown -R root:root  /etc/ld.so.conf
  sudo ldconfig
#+end_src
执行完毕后重新打开 shell 会话窗口即可生效。

至此，OpenSSL 3 已经成功安装，可以回到原来的章节继续阅读或尝试运行仓颉编译器了。

**** 参考链接

[[https://openssl-library.org/source/old/index.html][https://www.openssl.org/source/old/]]

** 安装仓颉工具链

#+begin_src bash
  tar xvf Cangjie-0.53.18-linux_x64.tar.gz
  source cangjie/envsetup.sh
#+end_src

*** 参考链接

[[https://docs.cangjie-lang.cn/docs/0.53.18/user_manual/source_zh_cn/first_understanding/install_Community.html#安装仓颉工具链][安装仓颉工具链]]

[[https://cangjie-lang.cn/download/0.53.18][Cangjie 0.53.18]]

** 运行第一个仓颉程序

首先，请在适当目录下新建一个名为 hello.cj 的文本文件，并向文件中写入以下仓颉代码：

#+begin_src c
  // hello.cj
main() {
    println("你好，仓颉")
}
#+end_src
在这段代码中，使用了仓颉的注释语法，可以在 // 符号之后写单行注释，也可以在一对 /* 和 */ 符号之间写多行注释，这与 C/C++ 等语言的注释语法相同。注释内容不影响程序的编译和运行。

然后，请在此目录下执行如下命令：
#+begin_src bash
cjc hello.cj -o hello
#+end_src

这里仓颉编译器会将 hello.cj 中的源代码编译为此平台上的可执行文件 hello，在命令行环境中运行此文件，将看到程序输出了如下内容：
#+begin_src bash
  $ ./hello
  你好，仓颉
#+end_src

*** 参考链接

[[https://docs.cangjie-lang.cn/docs/0.53.18/user_manual/source_zh_cn/first_understanding/hello_world.html#运行第一个仓颉程序][运行第一个仓颉程序]]
