---
title: 免费临时云盘
date: 2024-03-26T00:24:24.00+0800
tags: [tools]
---

* 参考链接：https://zhuanlan.zhihu.com/p/536805039

* 文叔叔 - 传文件，找文叔叔（大文件、永不限速）

官网：https://www.wenshushu.cn

文叔叔是一个简单快速的文件分享网盘，无需注册登陆，一键分享/下载文件，而且号称“永不限速”。

可以通过链接、二维码、取件码分享/获取文件，支持上传整个文件夹而无需压缩打包，设置访问密码、到期自动销毁等。

- 上传、下载不限速
- 单文件最大 5GB
- 免费空间 40GB
- 批量传文件、文件夹
- 所有数据加密传输，同步永久销毁
- 支持移动客户端和微信小程序

* 钛盘 - 超好用的文件中转站

官网：https://tmp.link

钛盘是一个不限速 & 无限空间的纯网页版临时文件分享网盘。

可以通过链接、二维码分享和下载文件，而且支持使用 IDM 等第三方下载工具下载。

- 无限空间、不限数量
- 单文件最大 10GB
- 文件保存时间 24h
- 支持 curl 和 wget 命令下载
- 纯网页版，无客户端

* Send Anywhere

官网：https://send-anywhere.com

Send Anywhere 是一款非常知名的跨平台文件传输工具，2012 年推出至今已经运营 10 年时间。

可以通过密匙、二维码、链接、邮件分享和下载文件。而且使用密匙传输时直接在两台设备间传输文件，不会存储在服务器上，更安全可靠。

有 Win、Mac、Linux、安卓、iOS、网页版和浏览器扩展等设备支持极全。

- 密匙和二维码 10 分钟内有效，链接 48h 有效
- 普通用户 10GB 服务器空间（分享链接）
- 支持点对点无限制传输
- Wi-Fi 直连传输
- 最全的平台客户端支持

* Wormhole - 简单、私密的文件共享

官网：https://wormhole.app

Wormhole 是一个简单私密的文件分享网站，支持端到端加密传输文件。

5GB 以下的文件，会在服务器上存储 24 小时；大于 5GB 的文件，通过点对点传输，直接发送给接收者，需要保持页面打开直到传输完毕。

- 点对点加密传输
- 最大 10GB 文件分享
- 通过分享链接、二维码下载文件
- 免下载预览图像、音频和视频
- 设置过期时间和下载次数
- 手动删除文件
