---
title: "windows热键大全"
date: 2024-03-28T00:02:35.87+0800
tags: ["windows", "tools"]
---

* 系统
电脑启动程序文件夹：shell:startup

Ctrl+.：按下后会在全角中文标点和半角英文标点之间切换

Alt+Esc：会立即将当前窗口切换到下一个在后台打开的窗口，切换顺序通常与 Alt + Tab 的列表顺序一致。

资源监视器：resmon.exe，可以在运行框输入resmon并运行以打开资源监视器

调出搜索框：Win+Q与Win+S

步骤记录器：psr

鼠标控制：win+r_main.cpl

网络管理：win+r_ncpa.cpl

cmd窗口查看windows的 C:\Windows\System32 的目录下相关后缀的文件：dir /a *.cpl或dir /a *.msc

以管理员身份打开cmd：按下Win + R键，打开"运行"对话框，在对话框中输入"cmd"，然后按下Ctrl + Shift + Enter键。

文件资源管理器打开多文件夹操作：用Ctrl选中多个连接或用shift选中连续文件夹，然后按住ctrl键，再同时双击其它未选中文件夹即可以多窗口的形式打开文件夹

打开系统：在开始菜单搜索xi（xitong）或者 system 或者 setting 可以弹出区别于老版控制面板的系统设置

调整窗口：win+z

步骤记录器：打开windows搜索菜单搜索步骤记录器并运行，可以录制操作步骤，停止录制时可以查看录制下来的操作

alt + space：打开窗口菜单

打开开始菜单：Ctrl + Esc

winget安装程序示例： winget install --id=Microsoft.WindowsTerminal -l "D:\Program Files (x86)"

打开控制台根节点：win+r_mmc

如何将kali linux安装在u盘上？

进入kali.org官网下载Live Boot，然后用rufus刻录到u盘上，rufus界面默认设置，除高级选项显示外围硬盘，然后写入镜像模式为以DD镜像写入，制作完成。

如何将porteus linux发行版安装在u盘上，在porteus.org找到任意版本镜像下载下来后用rufus刻录到u盘上即可，之后重启电脑通过u盘进入系统即可。

如何将tiny core linux安装在u盘上，到http://tinycorelinux.net/找到镜像下载之后再通过Etcher刻录进u盘即可。

高级操作：1、打开regedit；2、打开msconfig.exe(安全模式)；3、gpedit;

查看电脑端口状态：win+r_cmd_netstat

任务栏程式切换：win+t和win+shitf+t(倒着切换)

文件强制删除(针对权限不高的文件)：shift+delete

注销：win+r_logoff

打开窗口设置：Alt + Space

打开文件属性：Alt + Enter

创建虚拟桌面：ctrl+win+d

虚拟桌面间切换：win+ctrl+方向键

关闭虚拟桌面：ctrl+win+F4

从程式切换到桌面：win+m

打开虚拟键盘：Ctrl + Win + o

打开投影：Ctrl + Win + p

打开开始菜单：ctrl + esc

查看桌面：win+逗号

一键回到桌面：win+d

任务栏打开新应用：win+1..9

多个应用程式分屏：win+方向键

应用切换：alt+tab

显示任务视窗：win+tab

任务管理器：ctrl+shift+esc 或者 ctrl+alt+.

打开文档浏览器：win+e

新增视窗：ctrl+n

打开文档特定类型文件：ctrl+O

使用放大镜：win+加号键或减号键

捕捉屏幕：win+psr

快速截图：win+shift+s

使用操作中心：win+a

进入设置：win+i

与系统语音助手对话：win+c

使用系统游戏栏：win+g

锁住pc：win+L

打开高级系统设置：win+r->sysdm.cpl

退出桌面：ctrl+alt+delete

系统自带表情：win+句号

打印页面：ctrl+p

保存页面：ctrl+s

放大或缩小：ctrl+加号或等于键，ctrl+减号或杠键，ctrl+右括号或零键

资源监视器：Win+r_resmon/perfmon /res

打开设置的关于页面：Win+pouse

投影：win+p

框选识别文字：ctrl+alt+o

框选翻译文字：ctrl+alt+f

打开键盘：ctrl+win+o

重新创建notepad：Ctrl + Shift + N

打印机设置：ctrl+shift+p

使用命令提示符来注册电脑上全部的dll文件：for %1 in (%windir%\system32\*.dll) do regsvr32.exe /s %1

查找计算机：ctrl+win+f

切换到windows powershell：win+x

快速启动：C:\Users\Administrator\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup

一键关闭电脑所有软体：taskkill /F /FI "USERNAME eq Administrator" /FI "IMAGENAME ne explorer.exe" /FI "IMAGENAME ne dwm.exe"

一键关闭电脑所有软体：taskkill /F  /FI "IMAGENAME ne explorer.exe" /FI "IMAGENAME ne dwm.exe"

查看电脑连接过的wifi的密码：netsh wlan show profiles name=wifi名字 key=clear

连接无线设备：win+k

显示系统信息：按Win键，输入 msinfo并回车或直接搜索 系统信息

高级菜单：win+x

rss订阅：https://ynrss.herokuapp.com/

用cmd命令装逼：先color a回车，再dir /s回车即可

查看端口排错：netstart -ano | findsrt 50524

阻止所有弹窗的相关设置方法：win+r_control.exe_网络和internet_internet选项_隐私_启用弹出窗口阻止程序(B)_阻止

级别(高)_win+e_此电脑_管理_点开任务计划程序小箭头_任务计划程序库_把所有程序状态改为禁用

远程转接：win+r_control.exe_系统的安全_允许远程访问_允许远程连接到此计算机(L)——win+r_mstsc_输入对方电脑ip

查看端口排错：netstart -ano | findsrt 50524

如何查看系统信息：win+r_control.exe_系统_查看RAM的大小和处理器的速度

修复电脑损坏文件：win+r_chkdsk(回车)_sfc /scannow

清理电脑垃圾文件：win+r_cmd_%temp%和win+r_cleanmgr

进入启动文件夹（开机自启动）：shell:startup

电脑截图的6种方法：ctrl+alt+a（qq截图）、alt+a（微信截图）、shift+alt+a（企业微信截图）、win+shift+a（花样截图）、ctrl+alt+x（wps截图）、电脑自带截图小工具

删除字符串快捷键：ctrl + backspace

关闭cmd：taskkill /f /im cmd.exe

计算机性能实时检测程序：perfmon.msc

查看或修改电脑程序状态：msconfig

DirectX诊断工具也查询电脑具体配置：dxdiag

远程控制电脑，只需输入ip即可：mstsc

一键清理磁盘内垃圾：cleanmgr

在dos窗口查看当前路径：echo %pa%

下载网页视频的方法：F12_network(网络)_F5(刷新一下)_点击刷新出来的链接即可

上帝之眼(使用方法，把这串代码命名到一个新建的空文件夹之可)：GodMode.{ED7BA470-8E54-465E-825C-99712043E01C}

一键关闭cmd程式（bat文件）：start taskkill /f /im cmd.exe

电脑自带工具-哈希值校验：例如要校验 ideaIU-2018.1.exe ，正确做法是在文件所在文件夹输入 certutil -hashfile ideaIU-2018.1.exe sha256 ，即 certutil -hashfile + 文件名(包括后缀) + sha256 ;如果不加最后一个参数，则默认是这个 certutil -hashfile filename md5 ；还有一种方法是：Get-FileHash 文件路径 -Algorithm 校验的Hash值类型| Format-List

用vbs打开指定文件：createobject("wscript.shell").run "cmd /c start D:\__easyHelper__"

vbs设置循环次数：

dim s

do until s=999

s=s+1

msgbox"这里写窗口显示内容"

loop

999是循环次数，可以修改

查看电脑vbs的环境变量：进入cmd，输入set即可

在cmd窗口无限循环输出自定义文字：for /l %a in (0,0,1) do echo  自定义

可用来尝试激活电脑：slmgr /skms kms.03k.org

		slmgr /ato

快捷方式关机：创建快捷方式，输入slidetoshutdown,确定后再将快捷方式的名字改为自定义的即可

修复(清空)u盘的方法：win+r_cmd_diskpart_list disk_select disk 1(所要操作的磁盘序号)_clean

创建分区的方法：win+r_cmd_create partition primary_select partition 1(对应清空的磁盘序号)_active_format fs=ntfs quick

查看磁盘的相关修改参数：lsit disk

掌握win7的快捷键，没有鼠标您也从容使用系统：

一、Win键相关的快捷键

Win + Home 将所有使用中窗口以外的窗口最小化（和摇动使用中窗口一样意思）

Win + Space空格键 将所有桌面上的窗口透明化（和鼠标移到工作列的最右下角一样意思）

Win + ↑上方向键 最大化使用中窗口（和将窗口用鼠标拖到屏幕上缘一样意思）

Shift + Win + ↑上方向键 垂直最大化使用中窗口（但水平宽度不变）

Win +↓下方向键 最小化窗口／还原先前最大化的使用中窗口

Win +左／右方向键 窗口靠到屏幕的左右两侧（和将窗口用鼠标拖到左右边缘一样意思）

Shift + Win +左/右方向键 将窗口移到左、右屏幕（如果你有接双屏幕的话）工作列快速列

Win + 1~9 开启工作列上相对应的软件，从左到右依顺序为Win+1到Win+9

Shift + Win + 1~9 开启对应位置软件的一个新「分身」，例如firefox的话会是开新窗口（鼠标是Shift+点软件）

Ctrl + Win + 1~9 在对应位置软件已开的分身中切换

Alt + Win + 1~9 开启对应位置软件的右键选单

Ctrl + Shift + 鼠标点软件以管理员权限开启该软件

WIN +点击任务栏快捷方式 在此程序中新建一个实例

Win + (+/-)：　　　　　　 打开Windows放大、缩小功能

Win + G 在屏幕上的Gadget间切换

Win + X 打开移动中心

Win + D 显示桌面，最小化所有窗口

Win + E 打开资源管理器

Win + F 打开资源管理器搜索结果

Win + L 锁定计算机，回到登陆窗口

Win + M 最小化当前窗口

Win + P 投影机输出设定（仅屏幕、同步显示、延伸、仅投影机）

Win + R 打开运行窗口

Win + T 工作列的Alt+Tab

Win + U 打开控制面板轻松访问中心

Win + Break 打开控制面板系统属性

Win + Tab 打开Flip3D任务切换功能

二、Windows基础快捷键

F1 帮助

Ctrl+C ( Ctrl+Insert) 复制选中项目

Ctrl+X 剪切选中项目

Ctrl+V ( Shift+Insert) 粘贴选中项目

Ctrl+Z 撤销

Ctrl+Y 重做

Delete ( Ctrl+D) 删除选中项目至回收站

Shift+Delete 直接删除选中项目

F2 重命名选中项目

Ctrl+A 全选

F3 搜索

Alt+Enter 显示选中项目属性

Alt+F4 关闭当前项目或退出当前程序

Alt+空格 打开当前窗口的快捷方式菜单

Alt+Tab 在当前运行的窗口中切换

Ctrl+Alt+Tab 使用方向键在当前运行的窗口中切换

Ctrl+滚轮 改变桌面图标大小

win+Tab 开启Aero Flip 3-D

Ctrl+win +Tab 使用方向键在Aero Flip 3D程序中切换

Alt+Esc 在当前打开的程序间切换

F4 显示资源管理器的地址栏列表

Shift+F10 显示选中项目的快捷方式菜单

Ctrl+Esc 打开开始菜单

F10 激活当前窗口的菜单栏

F5 ( Ctrl+R) 刷新

Alt+↑ 资源管理区中返回文件夹的上一级菜单

Esc 取消当前操作

Ctrl+Shift+Esc 打开任务栏管理器

插入光盘时按住Shift 禁止CD/DVD的自动运行

右边或左边的Ctrl+Shift 改变阅读顺序

* hosts文件

#+begin_src bash

  # Copyright (c) 1993-2009 Microsoft Corp.
  #
  # This is a sample HOSTS file used by Microsoft TCP/IP for Windows.
  #
  # This file contains the mappings of IP addresses to host names. Each
  # entry should be kept on an individual line. The IP address should
  # be placed in the first column followed by the corresponding host name.
  # The IP address and the host name should be separated by at least one
  # space.
  #
  # Additionally, comments (such as these) may be inserted on individual
  # lines or following the machine name denoted by a '#' symbol.
  #
  # For example:
  #
  #      102.54.94.97     rhino.acme.com          # source server
  #       38.25.63.10     x.acme.com              # x client host

  # localhost name resolution is handled within DNS itself.
  #	127.0.0.1       localhost
  #	::1             localhost
#+end_src

* 浏览器

搜索标签页：Ctrl+shift+a

截图技巧：F12->Ctrl+Shift+p->截图/capture，中文是截图，英文是capture

打开开发模式：ctrl+shift+j

打开Chrome浏览器的任务管理器：shift+esc

打开/关闭书签栏：Ctrl + Shift + B

为所有标签页添加书签：Ctrl + Shift + D

打开删除数据器数据：Ctrl + Shift + Delete

批量提取一个网页里面的链接：可以先用正则表达式将链接提取出来，然后再用在线批量打开链接网站如a-site.cn/tool/kai

如何在网页上查看时间：点开F12，在控制台输入 document.write(document.lastModified); 指令即可

从新窗口打开链接：shift+D+鼠标左键点击链接进入跳转

分页之间切换：ctrl+1..8,ctrl+9到最后一个分页

从当前分布移动到下一个分页：ctrl+tab，反序切换：ctrl+shift+tab

关闭或新增分页：关闭分布ctrl+w,撤销关闭分布ctrl+shift+t，新增分页ctrl+t

快进、恢复、还原：ctrl+加号或等于键，ctrl+减号或杠键，ctrl+右括号或零键

跳到视频起始处：Fn+右括号或零键

视频进度起始或结尾切换以及页面滚动：Fn+方向键，空格配合shift反向滚动

添加书签：ctrl+d

书签管理：ctrl+shift+o

查看浏览记录：ctrl+h

查看下载：ctrl+j

移动到网址栏：ctrl+l

刷新页面：ctrl+r或F5

在同一页面切换链接：alt+左右方向键

网页查找：ctrl+f或F3

清除浏览器浏览数据：ctrl+shift+delete

查看网页原代码：ctrl+u

如何查看网站记录的密码：针对自动填入网站密码的网站，只需右键菜单点击检查选项查看关于密码的源代码，将密码的type="原名字"改为text后再点击网页密码的位置即可查看密码

搜索的快捷方式：在地址栏中输入搜索引擎后按tab即可直接搜索

在浏览器中从新窗口打开链接：shift+左键点击链接

关闭所有打开的标签页和浏览器：Ctrl + Shift + w

退出Chrome浏览器：


YouTube:

前一部：shift+p

后一部：shift+n

暂停：k

视频进度跳转：数字键(小跳转)、Fn+方向键(大跳转)

暂停：k

静音：m

油管的观看记录：youtube.com/feed/history


电影：

4个免费电影资源网站：imomoe.la、aiyy.tv、aidi.tv、cupfox.com


网站的访问技巧：

b站：search.bilibili.com/all?keyword=搜索内容

油管：https://www.youtube.com/results?search_query=搜索内容

百度：https://baidu.com/s?&word=1

360搜索：m.so.com/s?q=1

谷歌：google.com/search?q=1

github：github.com/search?q=1

you.com(搜索引擎)：you.com/search?q=1

